


stages:
  - install 
  - build
  - test

install-code:
  image: node:latest
  stage: install
  script:
    - npm install

build-code:
  image: maven:latest
  stage: build
  script:
    - npm install

unit-tests:
  stage: test
  script:
    - npm run test 