image: maven:latest,node:latest


stages:
  - install 
  - build
  - test

install-code:
  stage: install
  script:
    - npm install

build-code:
  stage: build
  script:
    - mvn compile

unit-tests:
  stage: test
  script:
    - mvn clean test