
stages:
    - build
    - deploy

build:
    stage: build
    image:  maven:3.8.6-openjdk-18
    script:
        - cd backend
        - cd PI
        - echo "Building app..."
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        expire_in: 1 week
        paths:
            - backend/PI/target/PI-0.0.1-SNAPSHOT.jar

deploy:
    stage: deploy
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H "$DEPLOY_SERVER_IP" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - ssh -i "$SSH_PRIVATE_KEY" ubuntu@$DEPLOY_SERVER_IP "mkdir carpeta deploy"