
stages:
  - install 
  - build


install-code:
  image: node:latest
  stage: install
  script:
    - npm install

build-code:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run 